# frontend builder
FROM node:20 AS builder

WORKDIR /app

# clean install dependencies
COPY ./frontend/package.json ./frontend/package-lock.json ./
RUN npm ci

# build the frontend
COPY ./frontend ./
RUN npm run build

# run the backend

FROM nginx:alpine

# Copy the built Vite files to the Nginx HTML directory
COPY --from=builder /app/dist /usr/share/nginx/html

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
