version: "4"

services:
  # nginx with static frontend and reverse proxy to backend
  frontier:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    volumes:
      - nginx_data:/usr/share/nginx/html:rw
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  # mailpit SMTP server for testing
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./volumes/mailpit:/data
    ports:
      - "${FORWARD_MAILPIT_PORT:-1025}:1025"
      - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  mail_buildr:
    build:
      context: ./react-email-starter
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

volumes:
  nginx_data:
